language: rust
matrix:
  include:
    - os: linux
      env: TARGET=armv7-unknown-linux-gnueabihf
      rust: nightly-2019-01-24
      dist: xenial
    - os: linux
      env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly-2019-01-24
      dist: xenial
    - os: osx
      rust: nightly-2019-01-24
sudo: true
env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib
addons:
  apt:
    packages:
      - libgtk-3-dev
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gtk+3 cairo atk; fi
  - rustup component add clippy
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y clang; fi
script:
  - rustc --version
  - RUST_BACKTRACE=1 cargo build --features link-with-stub
  - cargo clippy
