language: rust
dist: xenial
matrix:
  include:
    - os: linux
      env: TARGET=armv7-unknown-linux-gnueabihf
      rust: nightly-2019-01-24
      dist: trusty
    - os: linux
      env: TARGET=x86_64-apple-darwin
      rust: nightly-2019-01-24
      dist: trusty
    - os: osx
      rust: nightly-2019-01-24
sudo: true
env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib
    - RUSTFLAGS="-C link-arg=-Wl,--unresolved-symbols=ignore-all -C link-arg=-Wl,-undefined,dynamic_lookup"
addons:
  apt:
    packages:
      - libgtk-3-dev
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gtk+3 cairo atk; fi
  - rustup component add clippy
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y clang; fi
script:
  - rustc --version
  - RUST_BACKTRACE=1 cargo build
  - cargo clippy
