language: rust
matrix:
  include:
    - os: linux
      env:
        - TARGET=x86_64-unknown-linux-gnu
        - BINARY_SUFFIX=linux-amd64
      rust: nightly-2019-03-05
      dist: xenial
    - os: osx
      env:
        - BINARY_SUFFIX=macos
      rust: nightly-2019-03-05

sudo: true
env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib
    - RUST_BACKTRACE=1

addons:
  apt:
    packages:
      - libgtk-3-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gtk+3 cairo atk; fi
  - rustup component add clippy
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y clang; fi

script:
  - rustc --version
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"; cargo build --release; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cargo build --release; fi

before_deploy:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cargo install cargo-deb; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cargo deb --separate-debug-symbols; fi
  - mv target/release/ks-curve-tracer target/release/ks-curve-tracer-$BINARY_SUFFIX
  - mv target/release/ks-curve-tracer-cli target/release/ks-curve-tracer-cli-$BINARY_SUFFIX

deploy:
  provider: releases
  api_key:
    secure: Es7DL/1mzmXYdv///gY6OhJXqxwTwW8HYmtKxIBdGrG81AQ55B0OFgFF9SCwD45muNeic90MXKQERKq7qRxVTEVloVTHnVMtOuvNdFmmLfSgeVEYNvdBFYyg5APtJ/QZoY5/d+GvBmIpTf+e18SA1JcGR9qlgQcjC19BGm/66EuLk4Rn7MfxdOR/GULCU+3jsoaY6zbm0MtRuvdxY2cz+S60eGGBRNZ9JAwykhOH31yeXK+ytP+7rwhj8cX8Mf/feaIEVUNyNiU79t7+qFNHA6kSUset8pvRmBfABQWt76V23nknbs6S9fUK/08idVLKhzq7tnWrQ1KrgFfxUXG8BjOo4UeWjw5Fp6fHGd9ntlQFylg5OuigXZPeMg8/8wPpI7/Bge7v5nbP/2/WXf2XvtCaVUcejpCc04E14fzaduXDPa8/x1c8SBEmD4l5wT9yCnY7dY6ONPQ9R9FJvuFuRj6rAtAx0+XXEhuhL/2XCb2RJ7w7NY4XYWEPEe47RY6Yt66xYM/Gs5tt0B/fvv5Lm+Z0UqVYTEOu9WX1eHqnD3UGQlrQ7b3KCXsMocFv73hf2FRvG8KlkAr8f/EEfd88SFRSPWEN7/6AS5toxG+rSuDErbGH4UPqXKfOYKD3tzTZ0ngtkgV5SynGBhNCapUtnvOqNR6QI8S6p1TveslUMdI=
  file_glob: true
  file:
    - target/debian/ks-curve-tracer_*.deb
    - target/release/ks-curve-tracer-$BINARY_SUFFIX
    - target/release/ks-curve-tracer-cli-$BINARY_SUFFIX
  on:
    repo: knack-supply/curve-tracer
    tags: true
  skip_cleanup: true
  draft: true

cache:
  directories:
    - ~/.cargo
