environment:
  RUSTFLAGS: "-C link-arg=-Wl,--unresolved-symbols=ignore-all -C link-arg=-Wl,-undefined,dynamic_lookup"
  matrix:
    - RUST: nightly-2019-01-24
      BITS: 32
    - RUST: nightly-2019-01-24
      BITS: 64

install:
  - IF "%BITS%" == "32" SET ARCH=i686
  - IF "%BITS%" == "64" SET ARCH=x86_64
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host "%ARCH%-pc-windows-gnu" --default-toolchain %RUST% -y
  - SET PATH=C:\Users\appveyor\.cargo\bin;C:\msys64\mingw%BITS%\bin;%PATH%;C:\msys64\usr\bin
  - rustup component add clippy
  - rustc -Vv
  - cargo -Vv
  - pacman --noconfirm -S mingw-w64-%ARCH%-gtk3
  - pacman --noconfirm -S mingw-w64-%ARCH%-clang

build_script:
  - cargo clippy
  - cargo build

test: false
