environment:
  RUST_BACKTRACE: 1
  matrix:
    - RUST: stable
      BITS: 64

install:
  - SET ARCH=x86_64
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host "%ARCH%-pc-windows-gnu" --default-toolchain %RUST% -y
  - SET PATH=C:\msys64\mingw%BITS%\bin;C:\Users\appveyor\.cargo\bin;%PATH%;C:\msys64\usr\bin
  - rustc -Vv
  - cargo -Vv
  - pacman --noconfirm --needed -S mingw-w64-%ARCH%-gtk3 mingw-w64-%ARCH%-clang mingw-w64-%ARCH%-toolchain

build_script:
  - rustc --version
  - cargo build --release --features link-with-stub

test: false

deploy:
  description: release
  provider: GitHub
  auth_token:
    secure: "cdGt/v2Nj/1qGdf908Tij0R0d6IsfktJaf8EY+XTocWwQ3WBlABZCV5f+ScaOrLO"
  draft: true
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true

artifacts:
  - path: target/release/curve-tracer.exe
    name: curve-tracer.exe
  - path: target/release/curve-tracer-cli.exe
    name: curve-tracer-cli.exe

cache:
  - C:\msys64\var\cache\pacman\pkg
  - C:\Users\appveyor\.cargo
