environment:
  RUST_BACKTRACE: 1
  matrix:
#    - RUST: nightly-2019-01-24
#      BITS: 32
    - RUST: stable
      BITS: 64

install:
  - IF "%BITS%" == "32" SET ARCH=i686
  - IF "%BITS%" == "64" SET ARCH=x86_64
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host "%ARCH%-pc-windows-gnu" --default-toolchain %RUST% -y
  - SET PATH=C:\msys64\mingw%BITS%\bin;C:\Users\appveyor\.cargo\bin;%PATH%;C:\msys64\usr\bin
  - rustup component add clippy
  - rustc -Vv
  - cargo -Vv
  - pacman --noconfirm --needed -S mingw-w64-%ARCH%-gtk3 mingw-w64-%ARCH%-clang mingw-w64-%ARCH%-toolchain

build_script:
  - rustc --version
  - cargo build -vv --release --features link-with-stub
  - cargo clippy
  - 7z a digilent-waveforms-build-dir.zip target/release/build/digilent-waveforms-*

test: false

deploy:
  description: release
  provider: GitHub
  auth_token:
    secure: "cdGt/v2Nj/1qGdf908Tij0R0d6IsfktJaf8EY+XTocWwQ3WBlABZCV5f+ScaOrLO"
  artifact: "/target\\release\\curve-tracer(-cli)?\\.exe/"
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true

artifacts:
  - path: target/release/curve-tracer.exe
    name: curve-tracer.exe
  - path: target/release/curve-tracer-cli.exe
    name: curve-tracer-cli.exe
  - path: digilent-waveforms-build-dir.zip
    name: build-debug

cache:
  - C:\msys64\var\cache\pacman\pkg
  - C:\Users\appveyor\.cargo
